name: bot-signoff

"on":
  pull_request:
  workflow_dispatch:

jobs:
  signoff:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: cashapp/activate-hermit@v1
      - run: task signoff
