name: bot-signoff

"on":
  pull_request:
  workflow_dispatch:

jobs:
  signoff:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: cashapp/activate-hermit@v1
      - run: task signoff
